# Generated by Django 5.0.4 on 2024-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='this genere already exists', max_length=200, unique=True, verbose_name='genre name'),
        ),
    ]
