# Generated by Django 5.0.4 on 2024-05-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(error_messages={'unique': 'This genre already exists.'}, max_length=200, unique=True, verbose_name='genre name'),
        ),
    ]
