# Generated by Django 5.0.4 on 2024-05-03 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title cannot be empty', max_length=60, verbose_name='playlist title')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='playlist image')),
                ('created_date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_date', models.DateField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
