# Generated by Django 5.0.4 on 2024-05-03 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_followers_playlist_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_private',
            field=models.BooleanField(blank=True, default=True, verbose_name='is private'),
        ),
    ]
