# Generated by Django 5.0.4 on 2024-05-05 21:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_followers_alter_playlist_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 5), editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_private',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='is private'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='playlist image'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_date',
            field=models.DateField(default=datetime.date(2024, 5, 5), verbose_name='updated date'),
        ),
    ]
