# Generated by Django 5.0.4 on 2024-05-13 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlist_created_date_alter_playlist_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_generated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is generated'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 13), editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_date',
            field=models.DateField(default=datetime.date(2024, 5, 13), verbose_name='updated date'),
        ),
    ]
