# Generated by Django 5.0.4 on 2024-05-14 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_playlist_is_generated_alter_playlist_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 14), editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_date',
            field=models.DateField(default=datetime.date(2024, 5, 14), verbose_name='updated date'),
        ),
    ]
