# Generated by Django 5.0.4 on 2024-05-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_alter_playlist_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='picture',
        ),
        migrations.AddField(
            model_name='playlist',
            name='picture_url',
            field=models.CharField(blank=True, default='sfy-firebase.appspot.com/playlists_pictures/defaultplaylist.png', max_length=255, null=True, verbose_name='playlist picture'),
        ),
    ]
