# Generated by Django 5.0.4 on 2024-05-16 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_alter_playlist_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updated date'),
        ),
    ]
