# Generated by Django 5.0.4 on 2024-05-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_alter_playlist_created_date_and_more'),
        ('song', '0013_remove_song_albums_remove_playlistsongs_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistsSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
            options={
                'db_table': 'playlists_songs',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', through='playlist.PlaylistsSongs', to='song.song'),
        ),
    ]
