# Generated by Django 5.0.4 on 2024-05-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_alter_genre_name'),
        ('playlist', '0010_playlistssongs_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='major_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='genre.genre'),
        ),
    ]
