# Generated by Django 5.0.4 on 2024-05-03 21:48

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_userfollowers_customuser_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='author description')),
                ('header_picture', models.ImageField(blank=True, upload_to='', verbose_name='header picture')),
                ('is_author', models.BooleanField(blank=True, default=True, verbose_name='is user author')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.customuser',),
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
