# Generated by Django 5.0.4 on 2024-05-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='header_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='header picture'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='is user author'),
        ),
    ]
