# Generated by Django 5.0.4 on 2024-05-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_header_picture_alter_author_is_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_author',
        ),
    ]
