# Generated by Django 5.0.4 on 2024-05-03 21:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('playlist', '0003_alter_playlist_followers_alter_playlist_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
            ],
            options={
                'db_table': 'playlist_songs',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='song name')),
                ('duration', models.DurationField(blank=True, verbose_name='duration')),
                ('listened_num', models.IntegerField(blank=True, default=0, verbose_name='number of listens')),
                ('publication_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 3, 21, 54, 57, 656225, tzinfo=datetime.timezone.utc), verbose_name='publication date')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='picture')),
                ('playlists', models.ManyToManyField(blank=True, related_name='songs', through='song.PlaylistSongs', to='playlist.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song'),
        ),
        migrations.CreateModel(
            name='SongAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
            options={
                'db_table': 'song_authors',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(related_name='songs', through='song.SongAuthors', to='author.author'),
        ),
    ]
