# Generated by Django 5.0.4 on 2024-05-05 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlist_created_date_alter_playlist_followers_and_more'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='listened_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='number of listens'),
        ),
        migrations.AlterField(
            model_name='song',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', through='song.PlaylistSongs', to='playlist.playlist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 5, 21, 49, 2, 834703, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
