# Generated by Django 5.0.4 on 2024-05-13 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_publication_date_songgenres_song_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 13, 19, 14, 39, 514974, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
