# Generated by Django 5.0.4 on 2024-05-13 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 13, 19, 17, 55, 523714, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
