# Generated by Django 5.0.4 on 2024-05-14 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_alter_song_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 14, 20, 26, 15, 650058, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
