# Generated by Django 5.0.4 on 2024-05-14 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_alter_song_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='picture',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.CharField(default='sfy-firebase.appspot.com/songs/audio/nevergonnagiveyouup.mp3', max_length=500, verbose_name='audio URL'),
        ),
        migrations.AddField(
            model_name='song',
            name='picture_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='picture URL'),
        ),
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 14, 21, 3, 19, 791186, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
