# Generated by Django 5.0.4 on 2024-05-14 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_remove_song_picture_song_audio_url_song_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 14, 22, 34, 49, 540429, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
