# Generated by Django 5.0.4 on 2024-05-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_alter_song_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 15, 14, 34, 21, 468664, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
