# Generated by Django 5.0.4 on 2024-05-15 22:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_created_date_alter_album_publish_date'),
        ('song', '0010_alter_song_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 15, 22, 14, 9, 95756, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
        migrations.AlterModelTable(
            name='playlistsongs',
            table='playlists_songs',
        ),
        migrations.AlterModelTable(
            name='songauthors',
            table='songs_authors',
        ),
        migrations.AlterModelTable(
            name='songgenres',
            table='songs_genres',
        ),
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
            options={
                'db_table': 'albums_songs',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', through='song.AlbumSongs', to='album.album'),
        ),
    ]
