# Generated by Django 5.0.4 on 2024-05-16 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0012_alter_song_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='playlistsongs',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsongs',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlists',
        ),
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 16, 14, 11, 3, 115516, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
        migrations.DeleteModel(
            name='AlbumSongs',
        ),
        migrations.DeleteModel(
            name='PlaylistSongs',
        ),
    ]
