# Generated by Django 5.0.4 on 2024-05-17 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0015_alter_song_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 17, 16, 36, 53, 148633, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
