# Generated by Django 5.0.4 on 2024-05-18 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0016_alter_song_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 18, 13, 17, 52, 634254, tzinfo=datetime.timezone.utc), null=True, verbose_name='publication date'),
        ),
    ]
