# Generated by Django 5.0.4 on 2024-05-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customuser_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firebase_profile_picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture_url',
            field=models.CharField(blank=True, default='sfy-firebase.appspot.com/profile_pictures/defaultuser.png', max_length=255, null=True),
        ),
    ]
