# Generated by Django 5.0.4 on 2024-05-17 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0014_alter_song_publication_date'),
        ('user', '0009_customuser_is_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_time', models.DurationField(blank=True, null=True)),
                ('is_slider_used', models.BooleanField(default=False)),
                ('slider_stamp', models.DurationField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_listens',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='listens',
            field=models.ManyToManyField(blank=True, null=True, through='user.UserListens', to='song.song'),
        ),
    ]
