# Generated by Django 5.0.4 on 2024-05-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userlistens_customuser_listens'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlistens',
            table='user_listens',
        ),
    ]
