# Generated by Django 5.0.4 on 2024-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userlistens_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistens',
            name='is_slider_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
