# Generated by Django 5.0.4 on 2024-05-13 19:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_alter_author_header_picture_alter_author_is_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title cannot be empty', max_length=60, verbose_name='album title')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='album image')),
                ('created_date', models.DateField(default=datetime.date(2024, 5, 13), editable=False, verbose_name='created date')),
                ('publish_date', models.DateField(blank=True, default=datetime.date(2024, 5, 13), verbose_name='publish date')),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='followed_albums', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='author.author')),
            ],
        ),
    ]
