# Generated by Django 5.0.4 on 2024-05-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_album_picture_album_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 5, 15), editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 15), verbose_name='publish date'),
        ),
    ]
