# Generated by Django 5.0.4 on 2024-05-16 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_created_date_alter_album_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='publish date'),
        ),
    ]
