# Generated by Django 5.0.4 on 2024-05-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_created_date_alter_album_publish_date'),
        ('song', '0013_remove_song_albums_remove_playlistsongs_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumsSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
            options={
                'db_table': 'albums_songs',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', through='album.AlbumsSongs', to='song.song'),
        ),
    ]
