# Generated by Django 5.0.4 on 2024-05-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_albumssongs_album_songs'),
        ('genre', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='major_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='genre.genre'),
        ),
    ]
